### ISSUE TITLE
Didn't work in tensorflow1.6 with python 3.6 in win7

### ISSUE THREAD

**Issue by fourk-ty** [qhan1028/Fully-Convolutional-Networks#1]
![ques](https://user-images.githubusercontent.com/30832470/38121138-11e58c04-3400-11e8-93f1-3972847a3ecd.PNG)
I want it to work in my environment. What should I do. Which part should I changed? Or maybe there are some mistakes I made. I would be appreciated if anyone could help.
Now it shows a ValueError: can not feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'

**Comment by theadventureoflinko** [comment]
Similar error occurs in my environment (MacOS  10.14, python3.6.8, tensorflow-gpu 1.1.0 ).
In my case, error message was as following:
```
Traceback (most recent call last):
  File "fcn.py", line 317, in <module>
    main()
  File "fcn.py", line 246, in main
    images[i] = augment(im, flip_prob, aug_type, randoms)
ValueError: could not broadcast input array from shape (13,13,3) into shape (224,224,3)
```

**Comment by Johncheng1** [comment]
@theadventureoflinko  Have you solved this problem?

**Comment by theadventureoflinko** [comment]
@Johncheng1  No, still in trouble.

**Comment by DarkFunct** [comment]
执行 python3.5 fcn.py -m test 后 Res目录下生成的inp_0.png   pred_0.png
为什么会一片黑呢？？
![inp_0](https://user-images.githubusercontent.com/38775458/60184365-80fc2e80-985a-11e9-9f2a-a1915487aa56.png)
![pred_0](https://user-images.githubusercontent.com/38775458/60184402-91aca480-985a-11e9-9586-7affdeafb895.png)
